export const boardConfig = [{id: '1', value: 'none'},
                            {id: '2', value: 'none'},
                            {id: '3', value: 'none'},
                            {id: '4', value: 'none'},
                            {id: '5', value: 'none'},
                            {id: '6', value: 'none'},
                            {id: '7', value: 'none'},
                            {id: '8', value: 'none'},
                            {id: '9', value: 'none'},
                            {id: '10', value: 'none'},
                            
                            {id: '10', value: 'none'},
                            {id: '11', value: 'b'},
                            {id: '12', value: 'none'},
                            {id: '13', value: 'b'},
                            {id: '14', value: 'none'},
                            {id: '15', value: 'b'},
                            {id: '16', value: 'none'},
                            {id: '17', value: 'b'},
                            {id: '18', value: 'none'},
                            {id: '19', value: 'b'},
                            
                            {id: '20', value: 'none'},
                            {id: '21', value: 'b'},
                            {id: '22', value: 'none'},
                            {id: '23', value: 'b'},
                            {id: '24', value: 'none'},
                            {id: '25', value: 'b'},
                            {id: '26', value: 'none'},
                            {id: '27', value: 'b'},
                            {id: '28', value: 'none'},
                            {id: '29', value: 'b'},
                            
                            {id: '30', value: 'none'},
                            {id: '31', value: 'b'},
                            {id: '32', value: 'none'},
                            {id: '33', value: 'b'},
                            {id: '34', value: 'none'},
                            {id: '35', value: 'b'},
                            {id: '36', value: 'none'},
                            {id: '37', value: 'b'},
                            {id: '38', value: 'none'},
                            {id: '39', value: 'b'},
                            
                            {id: '40', value: 'none'},
                            {id: '41', value: 'none'},
                            {id: '42', value: 'none'},
                            {id: '43', value: 'none'},
                            {id: '44', value: 'none'},
                            {id: '45', value: 'none'},
                            {id: '46', value: 'none'},
                            {id: '47', value: 'none'},
                            {id: '48', value: 'none'},
                            {id: '49', value: 'none'},
                            
                            {id: '50', value: 'none'},
                            {id: '51', value: 'none'},
                            {id: '52', value: 'none'},
                            {id: '53', value: 'none'},
                            {id: '54', value: 'none'},
                            {id: '55', value: 'none'},
                            {id: '56', value: 'none'},
                            {id: '57', value: 'none'},
                            {id: '58', value: 'none'},
                            {id: '59', value: 'none'},
                            
                            {id: '60', value: 'w'},
                            {id: '61', value: 'none'},
                            {id: '62', value: 'w'},
                            {id: '63', value: 'none'},
                            {id: '64', value: 'w'},
                            {id: '65', value: 'none'},
                            {id: '66', value: 'w'},
                            {id: '67', value: 'none'},
                            {id: '68', value: 'w'},
                            {id: '69', value: 'none'},
                            
                            {id: '70', value: 'w'},
                            {id: '71', value: 'none'},
                            {id: '72', value: 'w'},
                            {id: '73', value: 'none'},
                            {id: '74', value: 'w'},
                            {id: '75', value: 'none'},
                            {id: '76', value: 'w'},
                            {id: '77', value: 'none'},
                            {id: '78', value: 'w'},
                            {id: '79', value: 'none'},
                            
                            {id: '80', value: 'w'},
                            {id: '81', value: 'none'},
                            {id: '82', value: 'w'},
                            {id: '83', value: 'none'},
                            {id: '84', value: 'w'},
                            {id: '85', value: 'none'},
                            {id: '86', value: 'w'},
                            {id: '87', value: 'none'},
                            {id: '88', value: 'w'},
                            {id: '89', value: 'none'},
                            
                            {id: '90', value: 'none'},
                            {id: '91', value: 'none'},
                            {id: '92', value: 'none'},
                            {id: '93', value: 'none'},
                            {id: '94', value: 'none'},
                            {id: '95', value: 'none'},
                            {id: '96', value: 'none'},
                            {id: '97', value: 'none'},
                            {id: '98', value: 'none'},
                            {id: '99', value: 'none'},
                        ]