export const boardConfig = [{id: '1', value: 'none'},
                            {id: '2', value: 'none'},
                            {id: '3', value: 'none'},
                            {id: '4', value: 'none'},
                            {id: '5', value: 'none'},
                            {id: '6', value: 'none'},
                            {id: '7', value: 'none'},
                            {id: '8', value: 'none'},
                            {id: '9', value: 'none'},
                            {id: '10', value: 'none'},
                            
                            {id: '9', value: 'none'},
                            {id: '10', value: 'b'},
                            {id: '11', value: 'none'},
                            {id: '12', value: 'b'},
                            {id: '13', value: 'none'},
                            {id: '14', value: 'b'},
                            {id: '15', value: 'none'},
                            {id: '16', value: 'b'},
                            {id: '16', value: 'none'},
                            {id: '16', value: 'b'},
                            
                            {id: '9', value: 'none'},
                            {id: '10', value: 'b'},
                            {id: '11', value: 'none'},
                            {id: '12', value: 'b'},
                            {id: '13', value: 'none'},
                            {id: '14', value: 'b'},
                            {id: '15', value: 'none'},
                            {id: '16', value: 'b'},
                            {id: '16', value: 'none'},
                            {id: '16', value: 'b'},
                            
                            {id: '9', value: 'none'},
                            {id: '10', value: 'b'},
                            {id: '11', value: 'none'},
                            {id: '12', value: 'b'},
                            {id: '13', value: 'none'},
                            {id: '14', value: 'b'},
                            {id: '15', value: 'none'},
                            {id: '16', value: 'b'},
                            {id: '16', value: 'none'},
                            {id: '16', value: 'b'},
                            
                            {id: '41', value: 'none'},
                            {id: '42', value: 'none'},
                            {id: '43', value: 'none'},
                            {id: '44', value: 'none'},
                            {id: '45', value: 'none'},
                            {id: '46', value: 'none'},
                            {id: '47', value: 'none'},
                            {id: '48', value: 'none'},
                            {id: '48', value: 'none'},
                            {id: '16', value: 'none'},
                            
                            {id: '49', value: 'none'},
                            {id: '50', value: 'none'},
                            {id: '51', value: 'none'},
                            {id: '52', value: 'none'},
                            {id: '53', value: 'none'},
                            {id: '54', value: 'none'},
                            {id: '55', value: 'none'},
                            {id: '56', value: 'none'},
                            {id: '56', value: 'none'},
                            {id: '16', value: 'none'},
                            
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            {id: '9', value: 'w'},
                            {id: '10', value: 'none'},
                            
                            {id: '57', value: 'none'},
                            {id: '58', value: 'none'},
                            {id: '59', value: 'none'},
                            {id: '60', value: 'none'},
                            {id: '61', value: 'none'},
                            {id: '62', value: 'none'},
                            {id: '63', value: 'none'},
                            {id: '64', value: 'none'},
                            {id: '64', value: 'none'},
                            {id: '16', value: 'none'},
                        ]